language: go

go:
  - 1.9.x
  - 1.10.x

before_install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout v0.13.1 && go install && cd -
  - make install-deps

script:
  - make cross-compile
